# Generated by Django 5.0.7 on 2025-03-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('pelo', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('descricao', models.TextField(default='')),
                ('informacao_extra', models.TextField(default='')),
                ('comportamento_pessoas', models.TextField(default='')),
                ('comportamento_animais', models.TextField(default='')),
                ('tipo', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato')], default='cao', max_length=4)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('adopted_date', models.DateField(auto_now_add=True, null=True)),
                ('adoptante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adoptantes.adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='animais.animal')),
            ],
        ),
    ]
