# Generated by Django 5.0.7 on 2025-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimages',
            name='imagem',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
