# Generated by Django 5.0.7 on 2025-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('cc', models.IntegerField(blank=True, null=True)),
                ('cc_expiraçao', models.DateField(blank=True, null=True)),
                ('rua', models.TextField(blank=True, default='', null=True)),
                ('localidade', models.TextField(blank=True, default='', null=True)),
                ('cidade', models.TextField(blank=True, default='', null=True)),
                ('codigo_postal', models.TextField(blank=True, default='', null=True)),
                ('telemovel', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profissao', models.TextField(blank=True, default='', null=True)),
                ('has_animal', models.BooleanField(default=False)),
            ],
        ),
    ]
