# Generated by Django 5.0.7 on 2025-02-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, max_length=2, null=True)),
                ('nif', models.IntegerField(blank=True, max_length=9, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('cc', models.IntegerField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('morada', models.TextField(blank=True, default='', null=True)),
                ('has_animal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('pelo', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('descricao', models.TextField(default='')),
                ('informacao_extra', models.TextField(default='')),
                ('comportamento_pessoas', models.TextField(default='')),
                ('comportamento_animais', models.TextField(default='')),
                ('cao', models.BooleanField(default=False)),
                ('gato', models.BooleanField(default=False)),
                ('idade', models.IntegerField(max_length=2)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('adopted_date', models.DateField(auto_now_add=True, null=True)),
                ('adoptante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.animal')),
            ],
        ),
    ]
