# Generated by Django 5.0.7 on 2025-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_morada_adoptante_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='gato',
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato')], default='cao', max_length=4),
        ),
    ]
